# Generated by Django 5.1.7 on 2025-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
